# Generated by Django 4.2.6 on 2023-10-24 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeartbeatRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.PositiveIntegerField(default=200)),
                ("elapsed", models.DecimalField(decimal_places=14, max_digits=32)),
                ("error", models.CharField(blank=True, max_length=100, null=True)),
                ("reason", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Request Log",
                "verbose_name_plural": "Request Log",
                "db_table": "heartbeat_request_log",
            },
        ),
    ]
